config/routes.rb
Rails.application.routes.draw do

  get '/' => "home#index", as: :home

  get '/about' => "pages#about"

  get '/about/:id' => "pages#about"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'application'

	def index
	

	end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	layout 'alt'

	def about
		@id = params[:id]

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Home index</h2>

<%= render "shared/nav", id: "Browse the pages"%>

app/views/layouts/alt.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment2Ror</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>This is the alternate layout</h1>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment2Ror</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>This is the regular layout</h1>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>


<%= render "shared/nav", id: "Here's the nav"%>

app/views/shared/_nav.html.erb
<%=id %>
<br>
<%= link_to "About", about_path %>
<%= link_to "Home", home_path %>